<footer>
    <div class="vu24">
        <h3>Greeliving</h3>
        <ul class="vu25">
            <li><a href="https://www.facebook.com/GreeLivingLearningHub"><i class="fa-brands fa-facebook"></i></a></li>
            <li><a href="tel:0984996598"><i class="fa-solid fa-phone"></i></a></li>
            <li><a href="mailto:info@greeliving.edu.vn"><i class="fa-solid fa-envelope"></i></a></li>
        </ul>
    </div>
    <div class="vu26">
        <p>COPYRIGHT &copy;2023 GREELIVING</p>
    </div>
</footer>