<header>
    <div id="header">
        <div class="vu19">
            <div class="vu20">
                <a href="candidate.php"><img src="images/brand_logo.png" class="vu21"></img></a> 
            </div>

            <ul class="vu22">
                <li><a href="search_course.php" class="vu23">Learning</a></li>
                <li><a href="search_job.php" class="vu23">Job Application</a></li>
            </ul>

            <div class="vu27">
                <a href="user.php" class="vu23"><i class="fa-solid fa-user"></i></a>
            </div>
        </div>
    </div>
</header>